# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0007_auto_20170803_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowtransition',
            name='trigger_time_period',
        ),
        migrations.RemoveField(
            model_name='workflowtransition',
            name='trigger_time_unit',
        ),
    ]
